[package]
name = "BG3D"
version = "0.1.0"
authors = ["tesseractcat <tesseractcats@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
random_color = "0.6.1"
futures = "0.3"
futures-util = "0.3.17"
names = { version = "0.12.0", default-features = false }
tokio = { version = "1", features = ["full"] }
tokio-stream = "0.1.7"
serde = { version = "1.0", features = ["derive"]}
serde_json = "1.0"
warp = { version = "0.3.1", features = ["compression", "tls"] }
rapier3d = { version = "0.11.1" }
